services:
  db:
    image: postgres
    volumes:
    - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    volumes:
    - ./.redis:/data
  auth:
    build: .
    command: ["/bin/sh", "-c", "cd demos/auth-express; npm i; npm start"]
    ports:
    - "5173:5173"
    env_file:
    - .env
  worker:
    build: .
    command: ["wait-for", "db:5432", "--", "npm", "run", "start:worker"]
    env_file:
    - .env
    volumes:
    - node_modules:/app/node_modules
    depends_on:
    - db
    - redis
  server:
    build: .
    command: ["wait-for", "db:5432", "--", "npm", "run", "start:server"]
    ports:
    - "3002:3002"
    env_file:
    - .env
    volumes:
    - .:/app/
    - node_modules:/app/node_modules
    depends_on:
    - db
    - redis
    - auth

volumes:
  node_modules: